### ISSUE TITLE
mac / Exception in thread "Thread-35" 

### ISSUE THREAD

**Issue by Jonnellinen** [sirjonasxx/G-Earth#106]
Hi guys!

I'm getting this when trying to run g-earth on mac (big sur) for habbo air. 

Any advice what to do?

My terminal:

```
-----------------------------------
OUTGOING (h:4000, l:48) --> [0][0][0]0[15] [0][28]MAC63-202105192052-961247021[0][6]FLASH3[0][0][0][1][0][0][0][0]
{out:ClientHello}{s:"MAC63-202105192052-961247021"}{s:"FLASH3"}{i:1}{i:0}
-----------------------------------
OUTGOING (h:894, l:2) --> [0][0][0][2][3]~
{out:InitDiffieHandshake}
-----------------------------------
INCOMING (h:2062, l:1030) --> [0][0][4][6][8][14][2][0]60c84dcdc209c41827572c76f2fff5e097579a9d7764eb86943455eb7baf0ca37fb114c4ee2c580073264b5058bd644bdc4f8acdee794d73e4edef81cff15409db5b611e475e2176871ce9c480d721361964bbf125c61b0642d2ea013fd1a35b710fd0727250b6372cca9cbfc53c650098739e9f3c2ea1165dd94d636a24bb3715265e40db575c94cd11e4aa9ec9c96d2c2274b2e2e9cb1c96b8503c4cc78c9068ab17a0664c9a9c06abddb1908df9cc503864bf1c1ee7cf3c6da32160785e85a905f756c1ef9b902d22a30c92ff790dcf032eb7b55e6a6397e7ff8db590bffb9ff6f4b877467c457325f01250f1988c13d554398881379087ac7c4899bd4d05[2][0]8aa3cdbda72e3beee84104d3c6df893eb524bbc892b380fc54d991287731fee89985ca40e45b083d25bee10664788d338b385f72088da8b5034ba40477d97636beda3595a4f88c050c1cdaca4cf606607cdf066fe1196c83542cd1a1b11f75f59d0263881a9642d0c6e0a5773530c4cddb7ac6f5a1b13b746452e817022a8702065755f51ff2d4b109bd94eb9d29d277979324bccea4767be4e4c523794618c433e9e92f0ca7a9575f992a91bdc202d187ff9d08a82931d88b50d915031c87ae98b320cd20a4319d704f522f8221a2637e5b8594c19c4c976b1f73977c64c96fabd14184e0730bef577b8f197c01faae57f95e7718e5457f4008ee91ee82bd53
{in:InitDiffieHandshake}{s:"60c84dcdc209c41827572c76f2fff5e097579a9d7764eb86943455eb7baf0ca37fb114c4ee2c580073264b5058bd644bdc4f8acdee794d73e4edef81cff15409db5b611e475e2176871ce9c480d721361964bbf125c61b0642d2ea013fd1a35b710fd0727250b6372cca9cbfc53c650098739e9f3c2ea1165dd94d636a24bb3715265e40db575c94cd11e4aa9ec9c96d2c2274b2e2e9cb1c96b8503c4cc78c9068ab17a0664c9a9c06abddb1908df9cc503864bf1c1ee7cf3c6da32160785e85a905f756c1ef9b902d22a30c92ff790dcf032eb7b55e6a6397e7ff8db590bffb9ff6f4b877467c457325f01250f1988c13d554398881379087ac7c4899bd4d05"}{s:"8aa3cdbda72e3beee84104d3c6df893eb524bbc892b380fc54d991287731fee89985ca40e45b083d25bee10664788d338b385f72088da8b5034ba40477d97636beda3595a4f88c050c1cdaca4cf606607cdf066fe1196c83542cd1a1b11f75f59d0263881a9642d0c6e0a5773530c4cddb7ac6f5a1b13b746452e817022a8702065755f51ff2d4b109bd94eb9d29d277979324bccea4767be4e4c523794618c433e9e92f0ca7a9575f992a91bdc202d187ff9d08a82931d88b50d915031c87ae98b320cd20a4319d704f522f8221a2637e5b8594c19c4c976b1f73977c64c96fabd14184e0730bef577b8f197c01faae57f95e7718e5457f4008ee91ee82bd53"}
-----------------------------------
OUTGOING (h:3599, l:516) --> [0][0][2][4][14][15][2][0]0e7e992bbc55081d448b755e4ca4acbf296f3f1babc52c007e1a7063145af7b7156aa57c1721b6b7da7712838f482c536ae0556fd2dfcc38298b2cdcba07d11510893391f8510ef5437099f449210912599b2c6fcce8f0edf2975daae89551c8ff6d510091837defb8dfdc88bab1051031b43d46481fa3b22fcd5139995332f2dd45278564daa13a6cffdb116c4d32725484d11ad738a12afe7b8ce6f10db37b33d7cc44fc0ed88a0a204d718217b57888392df03f81dea24e86579181f41fb8d2d4428c0ef3013941cda13ee2736682e1b27db62fd15c0cdff27dd5f78aac7d5a4817803f0a41aef448f1d590d32843afd3c3f8022c84c1d1b6fa5a502d8100
{out:CompleteDiffieHandshake}{s:"0e7e992bbc55081d448b755e4ca4acbf296f3f1babc52c007e1a7063145af7b7156aa57c1721b6b7da7712838f482c536ae0556fd2dfcc38298b2cdcba07d11510893391f8510ef5437099f449210912599b2c6fcce8f0edf2975daae89551c8ff6d510091837defb8dfdc88bab1051031b43d46481fa3b22fcd5139995332f2dd45278564daa13a6cffdb116c4d32725484d11ad738a12afe7b8ce6f10db37b33d7cc44fc0ed88a0a204d718217b57888392df03f81dea24e86579181f41fb8d2d4428c0ef3013941cda13ee2736682e1b27db62fd15c0cdff27dd5f78aac7d5a4817803f0a41aef448f1d590d32843afd3c3f8022c84c1d1b6fa5a502d8100"}
-----------------------------------
INCOMING (h:1938, l:517) --> [0][0][2][5][7][146][2][0]7d405130c85a41bcc3cc56906de942f23efc95bddfafb19ba5e30a6702d5122a901a4ecc1f7d3d51c8dddcd3a6ad8e640139261c784342fa20421c12504c1d6c21b79328cb1e9f9fc5c502757c91b5b7d8551f1f9fa7bae28aa80cde1e7b1955f2911e967962d1ef67279457b9977d73d5e4f71b3cbdd8fa59c95a87f45308a6188d7fb3fd74a84420719d0cb4427c96aa276eeed14f7f7bd83becbd883df5590d287e69ee0ecbe1d3cc489ca238e7e8758a3ccc5bc9ba31ff937cda17ab5dae484429897d3c60dee187705b6aadf29474912c31fd06cf8b6d4a70f363a76f24faf48e140462c74af5e239f9f877198276d3399a0a060ad207e698ea031d850a[0]
{in:CompleteDiffieHandshake}{s:"7d405130c85a41bcc3cc56906de942f23efc95bddfafb19ba5e30a6702d5122a901a4ecc1f7d3d51c8dddcd3a6ad8e640139261c784342fa20421c12504c1d6c21b79328cb1e9f9fc5c502757c91b5b7d8551f1f9fa7bae28aa80cde1e7b1955f2911e967962d1ef67279457b9977d73d5e4f71b3cbdd8fa59c95a87f45308a6188d7fb3fd74a84420719d0cb4427c96aa276eeed14f7f7bd83becbd883df5590d287e69ee0ecbe1d3cc489ca238e7e8758a3ccc5bc9ba31ff937cda17ab5dae484429897d3c60dee187705b6aadf29474912c31fd06cf8b6d4a70f363a76f24faf48e140462c74af5e239f9f877198276d3399a0a060ad207e698ea031d850a"}{b:false}
Exception in thread "Thread-35" java.lang.ArrayIndexOutOfBoundsException: 255
	at gearth.protocol.crypto.RC4.undoRc4(RC4.java:193)
	at gearth.protocol.memory.Rc4Obtainer.onSendFirstEncryptedMessage(Rc4Obtainer.java:129)
	at gearth.protocol.memory.Rc4Obtainer.lambda$onSendFirstEncryptedMessage$3(Rc4Obtainer.java:72)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by dorving** [comment]
Likely has to do with G-Mem input not being read. @Jonnellinen have u tried disabling SIP (https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection).
