### ISSUE TITLE
G-earth won't connect (macos)

### ISSUE THREAD

**Issue by yoitscarolinee** [sirjonasxx/G-Earth#129]
I'm on macOS Monterey 12.3.1
java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 1.8.0_331-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.331-b09, mixed mode)

terminal output:
`java.io.IOException: Cannot run program "/Applications/G-Earth/G-Mem": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at gearth.protocol.memory.habboclient.macOs.MacOsHabboClient.readPossibleBytes(MacOsHabboClient.java:89)
	at gearth.protocol.memory.habboclient.macOs.MacOsHabboClient.getRC4possibilities(MacOsHabboClient.java:124)
	at gearth.protocol.memory.Rc4Obtainer.lambda$onSendFirstEncryptedMessage$3(Rc4Obtainer.java:78)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
java.io.IOException: Cannot run program "/Applications/G-Earth/G-Mem": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at gearth.protocol.memory.habboclient.macOs.MacOsHabboClient.readPossibleBytes(MacOsHabboClient.java:89)
	at gearth.protocol.memory.habboclient.macOs.MacOsHabboClient.getRC4possibilities(MacOsHabboClient.java:124)
	at gearth.protocol.memory.Rc4Obtainer.lambda$onSendFirstEncryptedMessage$3(Rc4Obtainer.java:78)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
COULD NOT FIND RC4 TABLE`

**Comment by WiredSpast** [comment]
Did you create the certificate for G-Mem and are you running G-Earth using sudo?

**Comment by yoitscarolinee** [comment]
did not create a certificate for G-Mem, how should I do this?

**Comment by dorving** [comment]
@yoitscarolinee https://github.com/sirjonasxx/G-Earth/wiki/macOs-Installation-guide
