### ISSUE TITLE
Stuck at 76% - Maybe a RC4 problem

### ISSUE THREAD

**Issue by JohnnyAs1** [sirjonasxx/G-Earth#49]
Hi,

the Client stucks at 76%, and I don't know what to do. The Packetlogger-Window appears, but the terminal shows me a Exception.

The Exception:
Exception in thread "Thread-36" java.lang.ArrayIndexOutOfBoundsException: 255
	at gearth.protocol.crypto.RC4.undoRc4(RC4.java:193)
	at gearth.protocol.memory.Rc4Obtainer.onSendFirstEncryptedMessage(Rc4Obtainer.java:128)
	at gearth.protocol.memory.Rc4Obtainer.lambda$onSendFirstEncryptedMessage$5(Rc4Obtainer.java:75)
	at java.lang.Thread.run(Thread.java:748)

**Operating System**: Mac OS 10.15 Catalina
**Java:**
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

**Comment by XePeleato** [comment]
Hi, did you disable SIP (System Integrity Protection)? Maybe you have to, specially in the newest versions of macOs.

**Comment by JohnnyAs1** [comment]
@XePeleato Thank you a lot! Now its working; can you explain me maybe why we have to turn the SIP off?
