### ISSUE TITLE
Error opening

### ISSUE THREAD

**Issue by MiClobiMC** [sirjonasxx/G-Earth#56]
This is the error https://i.imgur.com/aWjhfG7.jpg

**Comment by sirjonasxx** [comment]
I would recommend reinstalling Java 8 for this one, can you try that?

**Comment by MiClobiMC** [comment]
I use this version Version 8 Update 251 What version do I have to use?

**Comment by sirjonasxx** [comment]
Should be good, 

also, can you try running from the commandline perhaps? maybe its an issue with the launcher
You need to open cmd as admin, navigate to the folder and enter "java -jar G-Earth.jar"

If that doesnt work, try reinstalling your java

**Comment by MiClobiMC** [comment]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: gearth/J12Main has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by sirjonasxx** [comment]
You downloaded the wrong G-Earth

download "G-Earth-1.0_windows_32bit.rar" or "G-Earth-1.0_windows_64bit.rar" and not the G-Earth_12 one, that one is for people that use java 12

**Comment by MiClobiMC** [comment]
ok thanks
