### ISSUE TITLE
Exception in Application start method on macOS

### ISSUE THREAD

**Issue by gurkentier** [sirjonasxx/G-Earth#63]
When running G-Earth on macOS I get the following exception on startup:
<img width="990" alt="Bildschirmfoto 2020-07-25 um 13 43 43" src="https://user-images.githubusercontent.com/46462486/88456338-2d08b280-ce7d-11ea-945e-bc916f17e341.png">

**Comment by gurkentier** [comment]
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: javafx.fxml.LoadException:
file:/Users/user/hack/gearth/G-Earth.jar!/gearth/ui/extensions/Extensions.fxml
file:/Users/user/hack/gearth/G-Earth.jar!/gearth/ui/G-Earth.fxml:31

	at javafx.fxml/javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2595)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml/javafx.fxml.FXMLLoader.access$2700(FXMLLoader.java:105)
	at javafx.fxml/javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1154)
	at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
	at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at gearth.Main.start(Main.java:34)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2591)
	... 15 more
Caused by: java.lang.ExceptionInInitializerError
	at org.fxmisc.richtext.ParagraphBox.<init>(ParagraphBox.java:95)
	at org.fxmisc.richtext.GenericStyledArea.createCell(GenericStyledArea.java:1582)
	at org.fxmisc.richtext.GenericStyledArea.lambda$new$11(GenericStyledArea.java:758)
	at org.fxmisc.flowless.CellPool.getCell(CellPool.java:28)
	at org.fxmisc.flowless.CellListManager.cellForItem(CellListManager.java:90)
	at org.reactfx.collection.MappedList.get(MappedList.java:27)
	at org.reactfx.collection.MemoizationListImpl.get(MemoizationList.java:99)
	at org.fxmisc.flowless.CellListManager.getCell(CellListManager.java:73)
	at org.fxmisc.flowless.CellPositioner.getSizedCell(CellPositioner.java:217)
	at org.fxmisc.flowless.CellPositioner.placeStartAt(CellPositioner.java:127)
	at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:220)
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:130)
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85)
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:80)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1204)
	at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1204)
	at org.fxmisc.flowless.VirtualFlow.visibleCells(VirtualFlow.java:230)
	at org.fxmisc.richtext.GenericStyledArea.<init>(GenericStyledArea.java:794)
	at org.fxmisc.richtext.StyledTextArea.<init>(StyledTextArea.java:33)
	at org.fxmisc.richtext.StyledTextArea.<init>(StyledTextArea.java:45)
	at org.fxmisc.richtext.StyleClassedTextArea.<init>(StyleClassedTextArea.java:18)
	at org.fxmisc.richtext.StyleClassedTextArea.<init>(StyleClassedTextArea.java:31)
	at org.fxmisc.richtext.StyleClassedTextArea.<init>(StyleClassedTextArea.java:41)
	at gearth.ui.extensions.logger.ExtensionLoggerController.initialize(ExtensionLoggerController.java:27)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2573)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at gearth.ui.extensions.logger.ExtensionLogger.<init>(ExtensionLogger.java:26)
	at gearth.ui.extensions.ExtensionsController.initialize(ExtensionsController.java:49)
	... 26 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make com.sun.javafx.scene.text.TextLayout javafx.scene.text.TextFlow.getTextLayout() accessible: module javafx.graphics does not "opens javafx.scene.text" to unnamed module @5ed9f45b
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:349)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:289)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:196)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:190)
	at org.fxmisc.richtext.TextFlowExt.<clinit>(TextFlowExt.java:37)
	... 56 more

**Comment by gurkentier** [comment]
Could you please bundle JavaFX and all modules with it? Thank you

**Comment by sirjonasxx** [comment]
@gurkentier since you said g-earth works now in #67 , what was the solution for this issue and can this be closed?
