### ISSUE TITLE
NullPointer Exception on startup

### ISSUE THREAD

**Issue by gurkentier** [sirjonasxx/G-Earth#69]
Sometimes when I start G-Earth, a Nullpointer Exception occurs. Could not find a way to reproduce reliably.
Exception in thread "Thread-36" java.lang.NullPointerException
	at gearth.protocol.packethandler.PacketHandler.sendToStream(PacketHandler.java:136)
	at gearth.protocol.connection.AsyncPacketSender.sendToServer(AsyncPacketSender.java:55)
	at gearth.protocol.connection.AsyncPacketSender.lambda$new$1(AsyncPacketSender.java:37)
	at java.lang.Thread.run(Thread.java:748)

**Comment by gurkentier** [comment]
MAC OS 10.15
Java 1.8

**Comment by sirjonasxx** [comment]
won't be able to reproduce with this amount of info, please reopen if this is still an issue
